---
namespace: cs2
image:
  repository: ghcr.io/kus/cs2-modded-server
  pullPolicy: Always
  tag: latest
service:
  type: LoadBalancer
  port: 27015
secrets:
  existingSecret: my-pre-created-secret
  # steamAccount: ""
  # apiKey: ""
  # rconPassword: ""
  # serverPassword: ""
  # duckToken: ""
  # duckDomain: ""
persistence:
  dataHostPath: /path/to/local/data-cs2/game/
  customHostPath: /path/to/local/data-cs2/custom_files/
nodeSelector:
  kubernetes.io/hostname: servername
env:
  exec: on_boot.cfg
  modBranch: master
  customFolder: custom_files
  bits: 64
  ip: ""
  tickrate: 128
  map: de_dust2
  maxPlayers: 14
  gameType: 0
  gameMode: 0
  mapGroup: mg_active
  lan: 0
  workshopCollection: 1234
watcher:
  enabled: true
  schedule: '*/15 * * * *'
  image:
    repository: ghcr.io/kus/cs2-modded-server
    tag: latest
