---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "cs2-server.fullname" .}}-install-script
  namespace: {{.Values.namespace}}
  labels:
    {{- include "cs2-server.labels" . | nindent 4}}
data:
  install_docker.sh: |
{{.Files.Get "scripts/install_docker.sh" | indent 4}}
