---
{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "cs2-server.fullname" .}}-secret
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  STEAM_ACCOUNT: {{.Values.secrets.steamAccount | quote}}
  API_KEY: {{.Values.secrets.apiKey | quote}}
  RCON_PASSWORD: {{.Values.secrets.rconPassword | quote}}
  SERVER_PASSWORD: {{.Values.secrets.serverPassword | quote}}
  {{- if .Values.secrets.duckToken }}
  DUCK_TOKEN: {{.Values.secrets.duckToken | quote}}
  {{- end }}
  {{- if .Values.secrets.duckDomain }}
  DUCK_DOMAIN: {{.Values.secrets.duckDomain | quote}}
  {{- end }}
{{- end}}
