---
{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "cs2-server.fullname" .}}-secret
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  STEAM_ACCOUNT: {{.Values.secrets.steamAccount | quote}}
  API_KEY: {{.Values.secrets.apiKey | quote}}
  RCON_PASSWORD: {{.Values.secrets.rconPassword | quote}}
  SERVER_PASSWORD: {{.Values.secrets.serverPassword | quote}}
{{- end}}
